"""removed uniques constraints in product table 

Revision ID: 0266b6774cf4
Revises: 566a0f18f129
Create Date: 2025-11-21 01:01:58.386586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0266b6774cf4'
down_revision: Union[str, Sequence[str], None] = '566a0f18f129'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('product_sku_key'), 'product', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('product_sku_key'), 'product', ['sku'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
