"""Add WebhookURL table and update Product model

Revision ID: 566a0f18f129
Revises: 52b4e3b74b49
Create Date: 2025-11-16 17:53:21.556559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '566a0f18f129'
down_revision: Union[str, Sequence[str], None] = '52b4e3b74b49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('webhookurl', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webhookurl', 'status')
    op.drop_column('product', 'status')
    # ### end Alembic commands ###
